---
services:
  # Wordpress Service
  wordpress:
    image: wordpress:latest
    container_name: ${APP_NAME}_wordpress
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - ${APP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./website:/var/www/html/
      - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_pma
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 64M
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}