version: '3.3'

services:
  # Wordpress Service
  wordpress:
    image: wordpress:latest
    container_name: ${APP_NAME}_wordpress
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - ${APP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    # volumes:
    #   - ./website:/var/www/html/

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}_mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - ./dbdata:/var/lib/mysql